# Generated by Django 5.0.7 on 2024-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='USER',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.BigIntegerField(),
        ),
    ]
