# Generated by Django 5.0.7 on 2024-08-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_complaint_reply_delete_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contact.user'),
        ),
    ]
